#
# Blog Settings
#
author: Kostas Konstantinidis
description: Codesennin's blog
url: http://codesennin.com
title: Codesennin
subtitle: [Some witty joke goes here]
gravatar_url: https://en.gravatar.com/userimage/5352439/89a8e18113f0f1c7ddff09b40882763c.png
subscribe_rss: http://feeds.feedburner.com/CodeSennin

# Github repositories
github_user: kotsaris
github_repo_url: https://github.com/kotsaris/codesennin

# Twitter
twitter_user: codesennin
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: codesennin
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-8762827-1


#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap