#
# Blog Settings
#
author: Kostas Konstantinidis
description: Codesennin's blog
url: https://codesennin.com
title: codesennin
subtitle: Just my thoughts
gravatar_url: https://s.gravatar.com/avatar/abe006dc565c07bf484f7138a260c09c?s=200
subscribe_rss: https://feeds.feedburner.com/CodeSennin

# Github repositories
github_user: kotsaris
github_repo_url: https://github.com/kotsaris/codesennin/

staticman:
  api: https://codesenninstatics.azurewebsites.net/v3/entry/github/kotsaris/codesennin/main/comments
  recaptcha:
    sitekey: "6LfrrQgqAAAAAFHQl9e6CXaFOGd5ZplgoRLhjU4Y"
    secret: "E99OmL5xTZ7azxb9ZneLYI1Z4DAhITXa6jdAmnHIsc9YvUxFXr5OG0so5jClZOksl9VStwhUgfNXJSYCIH6+wD39u38Q7D2zaTlz1MWk1JkPasxBzjG6vZ/NOVB1v8ZAl5aSPOr8eUEYZoLsy+/9lOGFbLLFreN7bPRKo3Rl9/IY4xC4GeS/DVj2y9woQmS0eq7HHkFUBSdUbjta+FOhFGp84c/MK+oqgEmGYj7cXLoEUfjjG6V7Ahcw2xusXSfdmJ1JeIUQUYSrj1u1dBU6TQJyG/tT1cT0J6CWJzvY9FruKFXe25+X2Xc0zlI2JYlzevWCFJlthR5pEQFCUq3XZQ=="

# Twitter
twitter_user: codesennin
twitter_tweet_button: true

#LinkedIn
linkedin_url: https://www.linkedin.com/in/kostaskonstantinidis/

# Google Analytics
google_analytics_tracking_id: G-04TG8936E4

#
# Jekyll Settings
#
markdown: kramdown
permalink: /archive/:year/:month/:day/:title/
paginate: 2
paginate_path: "page/:num"
category_dir: categories
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap